# -*- coding: utf-8 -*-
"""Semantic search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ufNq5rxqT28fvLoi5-tYp8EPQD_7zYE6
"""

# Install sentence-transformers for semantic search and rank-bm25 for keyword search
!pip install -q sentence-transformers rank-bm25

import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, util

# Sample corporate/tech dataset
corpus = [
    "How to hard-reset your iPhone 13 if the touch screen is completely frozen or unresponsive.", # Doc 0
    "Troubleshooting guide for iOS updates failing on newer Apple mobile devices.",              # Doc 1
    "The new Samsung Galaxy S26 Ultra features an advanced generative AI camera system.",         # Doc 2
    "Steps to recover a lost Google Pixel account recovery phrase or authentication token.",    # Doc 3
    "Fixing Wi-Fi connectivity drops and network configuration errors on Apple Macbook laptops.", # Doc 4
    "Why is my smartphone battery draining so quickly? Top power optimization tips.",            # Doc 5
]

print(f"Loaded database with {len(corpus)} technical documents.")

# Tokenize corpus for BM25 processing
tokenized_corpus = [doc.lower().split(" ") for doc in corpus]
bm25 = BM25Okapi(tokenized_corpus)

def sparse_search(query, top_n=5):
    """Executes keyword lookup and returns sorted document indices and raw scores."""
    tokenized_query = query.lower().split(" ")
    scores = bm25.get_scores(tokenized_query)
    # Sort indices by score descending
    top_indices = np.argsort(scores)[::-1][:top_n]

    # Return list of tuples: (doc_id, score)
    return [(idx, scores[idx]) for idx in top_indices if scores[idx] > 0]

# Quick verification test
print("Sparse test search for 'iPhone 13':", sparse_search("iPhone 13"))

# Initialize a lightweight, high-performance bi-encoder model
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate dense vector embeddings for the entire corpus
corpus_embeddings = embedding_model.encode(corpus, convert_to_tensor=True)

def dense_search(query, top_n=5):
    """Executes semantic search via cosine similarity and returns sorted indices and scores."""
    query_embedding = embedding_model.encode(query, convert_to_tensor=True)

    # Calculate cosine similarity matrix against all corpus documents
    cos_scores = util.cos_sim(query_embedding, corpus_embeddings)[0]

    # Sort top elements
    top_results = np.argsort(cos_scores.cpu().numpy())[::-1][:top_n]

    return [(int(idx), float(cos_scores[idx])) for idx in top_results]

# Quick verification test
print("Dense test search for 'pixels in camera':", dense_search("pixels in camera"))

def reciprocal_rank_fusion(sparse_results, dense_results, k=60, top_n=3):
    """
    Fuses rankings from separate systems using the Reciprocal Rank Fusion formula.
    Inputs are expected to be lists of tuples: (doc_id, score) sorted by relevance.
    """
    rrf_scores = {}

    # Process sparse rankings
    for rank, (doc_id, _) in enumerate(sparse_results):
        # rank starts at 0, so rank position is rank + 1
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Process dense rankings
    for rank, (doc_id, _) in enumerate(dense_results):
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0.0) + 1.0 / (k + (rank + 1))

    # Sort documents based on their combined RRF metrics
    fused_rankings = sorted(rrf_scores.items(), key=lambda item: item[1], reverse=True)

    return fused_rankings[:top_n]

def hybrid_search_engine(query, top_n=3):
    """Orchestrates both systems and fuses the output."""
    # 1. Gather deep recall arrays from both engines
    sparse_res = sparse_search(query, top_n=10)
    dense_res = dense_search(query, top_n=10)

    # 2. Fuse the rankings using RRF
    hybrid_res = reciprocal_rank_fusion(sparse_res, dense_res, k=60, top_n=top_n)

    # 3. Print pretty outputs for comparison
    print(f"\n==== TARGET QUERY: '{query}' ====")
    for rank, (doc_id, rrf_score) in enumerate(hybrid_res):
        print(f"\n[Rank {rank + 1}] (RRF Score: {rrf_score:.4f})")
        print(f"Document #{doc_id}: {corpus[doc_id]}")

# -----------------------------------------------------------------
# Execution Test 1: The Keyword Trap
# Query uses exact keyword terms from Doc 0, but conceptual theme of Doc 1
hybrid_search_engine("Apple mobile device issues")

# Execution Test 2: Multi-Concept Search
# Query matches semantic context of Doc 5 but specific tech hardware in Doc 4
hybrid_search_engine("Macbook laptop battery optimization")