# -*- coding: utf-8 -*-
"""FastAPI_nested_pydantic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NsnZXpx5JiVwKMjWS4af5qitAPUOyb61
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn "pydantic[email]" httpx2 pytest routers.orders

"""
main.py — FastAPI Application Entry Point
==========================================
Run:  uvicorn main:app --reload
Docs: http://127.0.0.1:8000/docs
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

#from routers.orders import router as orders_router

app = FastAPI(
    title="Order Management API",
    description=(
        "End-to-end FastAPI demo with **nested Pydantic models** and the "
        "**extension response pattern**.\n\n"
        "| Layer | Model |\n"
        "|---|---|\n"
        "| Leaf | `Address`, `Product` |\n"
        "| Composed | `OrderItem` (→ Product), `Customer` (→ Address) |\n"
        "| Top-level | `OrderCreate`, `Order` |\n"
        "| Extension | `OrderResponse` (→ Order + computed `summary`) |"
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/", tags=["Health"])
def health() -> dict:
    return {"status": "ok", "message": "Order Management API is running 🚀"}

"""
main.py — FastAPI Application Entry Point
==========================================
Run:  uvicorn main:app --reload
Docs: http://127.0.0.1:8000/docs
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from routers.orders import router as orders_router

app = FastAPI(
    title="Order Management API",
    description=(
        "End-to-end FastAPI demo with **nested Pydantic models** and the "
        "**extension response pattern**.\n\n"
        "| Layer | Model |\n"
        "|---|---|\n"
        "| Leaf | `Address`, `Product` |\n"
        "| Composed | `OrderItem` (→ Product), `Customer` (→ Address) |\n"
        "| Top-level | `OrderCreate`, `Order` |\n"
        "| Extension | `OrderResponse` (→ Order + computed `summary`) |"
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(orders_router)


@app.get("/", tags=["Health"])
def health() -> dict:
    return {"status": "ok", "message": "Order Management API is running 🚀"}

"""
models.py — Nested Pydantic Models
===================================
Domain: E-Commerce Order Management System

Hierarchy:
  Address
  Product
  OrderItem  → contains Product
  Customer   → contains Address
  Order      → contains Customer + List[OrderItem]
  OrderResponse (extension of Order with computed fields)
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, EmailStr, Field, field_validator, model_validator, ConfigDict


# ─────────────────────────────────────────
# Enums
# ─────────────────────────────────────────

class OrderStatus(str, Enum):
    PENDING   = "pending"
    CONFIRMED = "confirmed"
    SHIPPED   = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class PaymentMethod(str, Enum):
    CARD   = "card"
    UPI    = "upi"
    CASH   = "cash"
    WALLET = "wallet"


# ─────────────────────────────────────────
# Level 1 — Leaf Models
# ─────────────────────────────────────────

class Address(BaseModel):
    """Physical delivery / billing address."""
    model_config = ConfigDict(json_schema_extra={
        "example": {
            "street": "42 MG Road",
            "city": "Dehradun",
            "state": "Uttarakhand",
            "pincode": "248001",
            "country": "India",
        }
    })

    street:  str = Field(..., min_length=3)
    city:    str
    state:   str
    pincode: str = Field(..., pattern=r"^\d{6}$")
    country: str = Field(default="India")


class Product(BaseModel):
    """Catalogue product."""
    id:          UUID  = Field(default_factory=uuid4)
    name:        str   = Field(..., min_length=1)
    description: Optional[str] = None
    price:       float = Field(..., gt=0)
    sku:         str
    in_stock:    bool  = True

    @field_validator("price")
    @classmethod
    def price_precision(cls, v: float) -> float:
        return round(v, 2)


# ─────────────────────────────────────────
# Level 2 — Composed Models
# ─────────────────────────────────────────

class OrderItem(BaseModel):
    """A product line inside an order — nests Product."""
    product:  Product
    quantity: int   = Field(..., ge=1, le=100)
    discount: float = Field(default=0.0, ge=0.0, le=100.0, description="Discount % (0–100)")

    @property
    def line_total(self) -> float:
        discounted = self.product.price * (1 - self.discount / 100)
        return round(discounted * self.quantity, 2)


class Customer(BaseModel):
    """Buyer — nests Address."""
    id:               UUID     = Field(default_factory=uuid4)
    name:             str      = Field(..., min_length=2)
    email:            EmailStr
    phone:            str      = Field(..., pattern=r"^\+?[1-9]\d{9,14}$")
    shipping_address: Address
    billing_address:  Optional[Address] = None  # defaults to shipping_address if omitted

    @model_validator(mode="after")
    def set_billing_address(self) -> "Customer":
        if self.billing_address is None:
            self.billing_address = self.shipping_address
        return self


# ─────────────────────────────────────────
# Level 3 — Top-level Order Model
# ─────────────────────────────────────────

class OrderCreate(BaseModel):
    """Request body to create a new order."""
    customer:       Customer
    items:          List[OrderItem] = Field(..., min_length=1)
    payment_method: PaymentMethod
    notes:          Optional[str] = None

    @field_validator("items")
    @classmethod
    def items_not_empty(cls, v: List[OrderItem]) -> List[OrderItem]:
        if not v:
            raise ValueError("Order must contain at least one item.")
        return v


class Order(OrderCreate):
    """Full order as stored — extends OrderCreate with server-assigned fields."""
    id:         UUID        = Field(default_factory=uuid4)
    status:     OrderStatus = OrderStatus.PENDING
    created_at: datetime    = Field(default_factory=datetime.utcnow)
    updated_at: datetime    = Field(default_factory=datetime.utcnow)


# ─────────────────────────────────────────
# Level 4 — Extension / Response Model
# ─────────────────────────────────────────

class OrderSummary(BaseModel):
    """Computed summary injected into the response (extension pattern)."""
    subtotal:       float
    total_discount: float
    grand_total:    float
    item_count:     int


class OrderResponse(Order):
    """
    EXTENSION TASK:
    Extends Order with a read-only `summary` field computed on the fly.
    Demonstrates the 'response model as an extension' pattern in FastAPI.
    """
    summary: OrderSummary

    @classmethod
    def from_order(cls, order: Order) -> "OrderResponse":
        items = order.items
        subtotal       = sum(i.product.price * i.quantity for i in items)
        total_discount = sum(
            (i.product.price * i.quantity) - i.line_total for i in items
        )
        grand_total    = round(subtotal - total_discount, 2)

        return cls(
            **order.model_dump(),
            summary=OrderSummary(
                subtotal=round(subtotal, 2),
                total_discount=round(total_discount, 2),
                grand_total=grand_total,
                item_count=sum(i.quantity for i in items),
            )
        )

"""
database.py — In-Memory Store (simulates a DB layer)
=====================================================
Swap this for SQLAlchemy / Motor in production.
"""

from typing import Dict, Optional
from uuid import UUID


class OrderRepository:
    def __init__(self) -> None:
        self._store: Dict[UUID, Order] = {}

    def save(self, order: Order) -> Order:
        self._store[order.id] = order
        return order

    def get(self, order_id: UUID) -> Optional[Order]:
        return self._store.get(order_id)

    def list_all(self) -> list[Order]:
        return list(self._store.values())

    def update_status(self, order_id: UUID, status) -> Optional[Order]:
        order = self._store.get(order_id)
        if not order:
            return None
        # Pydantic v2: model_copy
        updated = order.model_copy(update={"status": status})
        self._store[order_id] = updated
        return updated

    def delete(self, order_id: UUID) -> bool:
        if order_id in self._store:
            del self._store[order_id]
            return True
        return False


# Singleton — injected via FastAPI dependency
_repo = OrderRepository()


def get_repository() -> OrderRepository:
    return _repo

"""
routers/orders.py — Order Endpoints
=====================================
Full CRUD + status-patch + summary extension.
"""

from typing import List
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status

router = APIRouter(prefix="/orders", tags=["Orders"])


# ── CREATE ──────────────────────────────────────────────────────────────────

@router.post(
    "/",
    response_model=OrderResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Place a new order",
)
def create_order(
    payload: OrderCreate,
    repo: OrderRepository = Depends(get_repository),
) -> OrderResponse:
    """
    Accepts a deeply nested `OrderCreate` body:
    - **customer** → name, email, phone, shipping_address (nested)
    - **items[]**  → each item embeds a full **product** object
    - **payment_method** enum
    - **notes** (optional)

    Returns an `OrderResponse` which *extends* the stored order with a
    computed **summary** block (subtotal, discounts, grand total, item count).
    """
    order = Order(**payload.model_dump())
    saved = repo.save(order)
    return OrderResponse.from_order(saved)


# ── READ ALL ────────────────────────────────────────────────────────────────

@router.get(
    "/",
    response_model=List[OrderResponse],
    summary="List all orders",
)
def list_orders(
    repo: OrderRepository = Depends(get_repository),
) -> List[OrderResponse]:
    return [OrderResponse.from_order(o) for o in repo.list_all()]


# ── READ ONE ────────────────────────────────────────────────────────────────

@router.get(
    "/{order_id}",
    response_model=OrderResponse,
    summary="Get a single order by ID",
)
def get_order(
    order_id: UUID,
    repo: OrderRepository = Depends(get_repository),
) -> OrderResponse:
    order = repo.get(order_id)
    if not order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order {order_id} not found.",
        )
    return OrderResponse.from_order(order)


# ── UPDATE STATUS (PATCH) ────────────────────────────────────────────────────

@router.patch(
    "/{order_id}/status",
    response_model=OrderResponse,
    summary="Update order status",
)
def update_order_status(
    order_id: UUID,
    new_status: OrderStatus,
    repo: OrderRepository = Depends(get_repository),
) -> OrderResponse:
    """
    Extension task: PATCH only the `status` field.
    Demonstrates partial update without re-validating the whole body.
    """
    order = repo.update_status(order_id, new_status)
    if not order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order {order_id} not found.",
        )
    return OrderResponse.from_order(order)


# ── DELETE ──────────────────────────────────────────────────────────────────

@router.delete(
    "/{order_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Cancel / delete an order",
)
def delete_order(
    order_id: UUID,
    repo: OrderRepository = Depends(get_repository),
) -> None:
    if not repo.delete(order_id):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order {order_id} not found.",
        )



"""
tests/test_orders.py — Pytest suite
=====================================
Run: pytest tests/ -v
"""

import sys, os
#sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest
from uuid import uuid4
from fastapi.testclient import TestClient


client = TestClient(app)

# ── Fixtures ────────────────────────────────────────────────────────────────

ORDER_PAYLOAD = {
    "customer": {
        "name": "Aarav Sharma",
        "email": "aarav@example.com",
        "phone": "+919876543210",
        "shipping_address": {
            "street": "42 MG Road",
            "city": "Dehradun",
            "state": "Uttarakhand",
            "pincode": "248001",
            "country": "India",
        },
    },
    "items": [
        {
            "product": {
                "name": "Wireless Headphones",
                "price": 2999.00,
                "sku": "WH-001",
            },
            "quantity": 2,
            "discount": 10.0,
        },
        {
            "product": {
                "name": "USB-C Cable",
                "price": 499.00,
                "sku": "UC-002",
            },
            "quantity": 3,
            "discount": 0.0,
        },
    ],
    "payment_method": "upi",
    "notes": "Leave at gate",
}


# ── Tests ────────────────────────────────────────────────────────────────────

def test_health():
    r = client.get("/")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"


def test_create_order_returns_summary():
    r = client.post("/orders/", json=ORDER_PAYLOAD)
    assert r.status_code == 201
    data = r.json()

    # Extension model check
    assert "summary" in data
    summary = data["summary"]
    assert summary["item_count"] == 5  # 2+3
    # subtotal = 2*2999 + 3*499 = 5998 + 1497 = 7495
    assert summary["subtotal"] == 7495.0
    # discount on item1 = 10% of 5998 = 599.8
    assert summary["total_discount"] == pytest.approx(599.8, rel=1e-3)
    assert summary["grand_total"] == pytest.approx(6895.2, rel=1e-3)


def test_create_order_nested_fields():
    r = client.post("/orders/", json=ORDER_PAYLOAD)
    assert r.status_code == 201
    data = r.json()

    # Nested customer → address
    assert data["customer"]["shipping_address"]["pincode"] == "248001"
    # billing_address defaults to shipping
    assert data["customer"]["billing_address"]["city"] == "Dehradun"

    # Nested item → product
    assert data["items"][0]["product"]["name"] == "Wireless Headphones"


def test_list_orders():
    client.post("/orders/", json=ORDER_PAYLOAD)
    r = client.get("/orders/")
    assert r.status_code == 200
    assert isinstance(r.json(), list)
    assert len(r.json()) >= 1


def test_get_order_by_id():
    create_r = client.post("/orders/", json=ORDER_PAYLOAD)
    order_id = create_r.json()["id"]

    r = client.get(f"/orders/{order_id}")
    assert r.status_code == 200
    assert r.json()["id"] == order_id


def test_get_order_not_found():
    r = client.get(f"/orders/{uuid4()}")
    assert r.status_code == 404


def test_update_order_status():
    create_r = client.post("/orders/", json=ORDER_PAYLOAD)
    order_id = create_r.json()["id"]

    r = client.patch(f"/orders/{order_id}/status?new_status=confirmed")
    assert r.status_code == 200
    assert r.json()["status"] == "confirmed"


def test_delete_order():
    create_r = client.post("/orders/", json=ORDER_PAYLOAD)
    order_id = create_r.json()["id"]

    del_r = client.delete(f"/orders/{order_id}")
    assert del_r.status_code == 204

    get_r = client.get(f"/orders/{order_id}")
    assert get_r.status_code == 404


def test_invalid_pincode():
    bad_payload = {**ORDER_PAYLOAD}
    bad_payload["customer"] = {
        **ORDER_PAYLOAD["customer"],
        "shipping_address": {**ORDER_PAYLOAD["customer"]["shipping_address"], "pincode": "12AB"},
    }
    r = client.post("/orders/", json=bad_payload)
    assert r.status_code == 422


def test_empty_items_rejected():
    bad_payload = {**ORDER_PAYLOAD, "items": []}
    r = client.post("/orders/", json=bad_payload)
    assert r.status_code == 422

import asyncio
import nest_asyncio
import uvicorn

nest_asyncio.apply()

config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
server = uvicorn.Server(config)

# Run the server as an asyncio task to avoid event loop conflicts in Colab
asyncio.create_task(server.serve())

!pip install ipytest -q

import ipytest
ipytest.autoconfig()

# Commented out IPython magic to ensure Python compatibility.
# %%ipytest -v